require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ResponsesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Response. As you add validations to Admin::Response, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ResponsesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_responses as @admin_responses" do
      response = Admin::Response.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_responses).should eq([response])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_response as @admin_response" do
      response = Admin::Response.create! valid_attributes
      get :show, {:id => response.to_param}, valid_session
      assigns(:admin_response).should eq(response)
    end
  end

  describe "GET new" do
    it "assigns a new admin_response as @admin_response" do
      get :new, {}, valid_session
      assigns(:admin_response).should be_a_new(Admin::Response)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_response as @admin_response" do
      response = Admin::Response.create! valid_attributes
      get :edit, {:id => response.to_param}, valid_session
      assigns(:admin_response).should eq(response)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Response" do
        expect {
          post :create, {:admin_response => valid_attributes}, valid_session
        }.to change(Admin::Response, :count).by(1)
      end

      it "assigns a newly created admin_response as @admin_response" do
        post :create, {:admin_response => valid_attributes}, valid_session
        assigns(:admin_response).should be_a(Admin::Response)
        assigns(:admin_response).should be_persisted
      end

      it "redirects to the created admin_response" do
        post :create, {:admin_response => valid_attributes}, valid_session
        response.should redirect_to(Admin::Response.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_response as @admin_response" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Response.any_instance.stub(:save).and_return(false)
        post :create, {:admin_response => {}}, valid_session
        assigns(:admin_response).should be_a_new(Admin::Response)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Response.any_instance.stub(:save).and_return(false)
        post :create, {:admin_response => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_response" do
        response = Admin::Response.create! valid_attributes
        # Assuming there are no other admin_responses in the database, this
        # specifies that the Admin::Response created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Response.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => response.to_param, :admin_response => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested admin_response as @admin_response" do
        response = Admin::Response.create! valid_attributes
        put :update, {:id => response.to_param, :admin_response => valid_attributes}, valid_session
        assigns(:admin_response).should eq(response)
      end

      it "redirects to the admin_response" do
        response = Admin::Response.create! valid_attributes
        put :update, {:id => response.to_param, :admin_response => valid_attributes}, valid_session
        response.should redirect_to(response)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_response as @admin_response" do
        response = Admin::Response.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Response.any_instance.stub(:save).and_return(false)
        put :update, {:id => response.to_param, :admin_response => {}}, valid_session
        assigns(:admin_response).should eq(response)
      end

      it "re-renders the 'edit' template" do
        response = Admin::Response.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Response.any_instance.stub(:save).and_return(false)
        put :update, {:id => response.to_param, :admin_response => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_response" do
      response = Admin::Response.create! valid_attributes
      expect {
        delete :destroy, {:id => response.to_param}, valid_session
      }.to change(Admin::Response, :count).by(-1)
    end

    it "redirects to the admin_responses list" do
      response = Admin::Response.create! valid_attributes
      delete :destroy, {:id => response.to_param}, valid_session
      response.should redirect_to(admin_responses_url)
    end
  end

end
